readHexDigitFromString:
                jsr readDigitFromString
                bcs LDE2B       ; taken if digit
                and #$DF        ; convert to upper case
                cmp #'F'+1
                bcs LDE13       ; taken if not hex digit
                cmp #'A'
                bcc LDE13       ; taken if not hex digit
                php
                sbc #'A'-10     ; convert to number
                plp
LDE2B:
                iny
                rts
